type: noatcards
contents:
  - file: c-(programming-language)/c-quiz.md
  - file: dotnet-framework/dotnet-framework-quiz.md
  - file: scala/scala-quiz.md
  - file: microsoft-excel/microsoft-excel-quiz.md
  - file: spring-framework/spring-framework-quiz.md
  - file: kotlin/kotlin-quiz.md
  - file: bash/bash-quiz.md
  - file: seo/search-engine-optimization-quiz.md
  - file: wordpress/wordpress-quiz.md
  - file: google-analytics/google-analytics-quiz.md
  - file: agile-methodologies/agile-methodologies-quiz.md
  - file: aws/aws-quiz.md
  - file: quickbooks/quickbooks-quiz.md
  - file: microsoft-project/microsoft-project-quiz.md
  - file: linux/linux-assesment.md
  - file: php/php-quiz.md
  - file: r/r-quiz.md
  - file: android/android-quiz.md
  - file: git/git-quiz.md
  - file: python/python-quiz.md
  - file: matlab/matlab-quiz.md
  - file: ruby-on-rails/ruby-on-rails-quiz.md
  - file: django/django-quiz.md
  - file: mongodb/mongodb-quiz.md
  - file: microsoft-power-bi/microsoft-power-bi-quiz.md
  - file: aws-lambda/aws-lambda-quiz.md
  - file: css/css-quiz.md
  - file: node.js/node.js-quiz.md
  - file: vba/vba-quiz.md
  - file: adobe-photoshop/adobe-photoshop-quiz.md
  - file: javascript/javascript-quiz.md
  - file: json/json-quiz.md
  - file: java/java-quiz.md
  - file: rest-api/rest-api-quiz.md
  - file: hadoop/hadoop-quiz.md
  - file: microsoft-power-point/microsoft-power-point-quiz.md
  - file: adobe-illustrator/adobe-illustrator-quiz.md
  - file: machine-learning/machine-learning-quiz.md
  - file: objective-c/objective-c-quiz.md
  - file: nosql/nosql-quiz.md
  - file: microsoft-word/microsoft-word-quiz.md
  - file: sharepoint/sharepoint-quiz.md
  - file: google-cloud-platform/gcp-quiz.md
  - file: jquery/jquery-quiz.md
  - file: swift/swift-quiz.md
  - file: angularjs/angularjs-quiz.md
  - file: t-sql/t-sql-quiz.md
  - file: c++/c++quiz.md
  - file: windows-server/windows-server-quiz.md
  - file: react/reactjs-quiz.md
  - file: mysql/mysql-quiz.md
  - file: microsoft-access/microsoft-access.md
  - file: maven/maven-quiz.md
  - file: oop/object-oriented-programming-quiz.md
  - file: oop/oops.md
  - file: adobe-premiere-pro/adobe-premiere-pro-quiz.md
  - file: xml/xml-quiz.md
  - file: microsoft-outlook/microsoft-outlook-quiz.md
  - file: html/html-quiz.md
  - file: microsoft-azure/microsoft-azure-quiz.md
  - file: visio/visio-quiz.md
  - file: c#/c-sharp-quiz.md
